import type { NextPage } from 'next'
import { FormEvent, FormEventHandler, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type Follower = {
  pk: string,
  full_name: string,
  profile_pic_url: string,
  username: string

}
const Home: NextPage = () => {
  const [followers, setFollowers] = useState<Follower[]>([])
  const [username, setUsername] = useState<string>("")
  
  async function submit (){
    const res = await fetch('/api/profile')
    const profiles: Follower[] = await res.json()
    setFollowers(profiles);
  }
  const handleSearch = async (event: FormEvent) => {
    event.preventDefault()

    const res = await fetch(
      `api/profile/${username}`
    )

    const profiles: Follower[] = await res.json()
    console.log(profiles)
    setFollowers(profiles);

    // result.user => 'Ada Lovelace'
  }

  return (
    <div className="w-screen h-screen bg-zinc-800" >
      <Head>
        <title>Insta-Save</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-800 text-center min-h-[95%] text-gray-200 m-auto">
        <h1 className="p-4  text-3xl">
          Insta-Save
        </h1>

        <p className="mx-auto w-1/3" >
          Salve os seus dados do instagram e proteja-se de uma eventual perda de conta.
        </p>
        <div className="p-4"></div>
        <form onSubmit={handleSearch}>

        <input placeholder="@user.name" onChange={e => setUsername((e.target.value))} className="p-0.5 text-zinc-800 mx-2"></input>
        <button onClick={()=> submit()} className="bg-zinc-400 px-4 py-1 rounded-full">Enviar</button>
        </form>
        <div className="mx-auto w-3/4 bg-gray-200 grid grid-cols-6">
        {followers.map((f,index)=>
          <div className="py-1" key={index}>
            <a href={`https://instagram.com/${f.username}`}>
            <h1 className="text-black">{f.full_name}</h1>

            <Image width={60} height={60} className="rounded-full" src={f.profile_pic_url}></Image>
            </a>
          </div>
          
        )}
        </div>
      </main>

      <footer className="text-center text-gray-200" >
        vogelcodes
      </footer>
    </div>
  )
}

export default Home
